services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./backups:/tmp/backups
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    platform: linux/amd64
    depends_on:
      - sqlserver
    volumes:
      - ./scripts:/tmp/scripts
    command: /bin/bash /tmp/scripts/restore.sh