services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./backups:/tmp/backups
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"